import chalk from 'chalk';
const log = console.log;
log(chalk.green('Welcome to the program'));
log(chalk.red('Welcome to the program'));
log(chalk.yellow('Welcome to the program'));
log(chalk.cyanBright('Welcome to the program'));
log(chalk.grey('Welcome to the program'));
log(chalk.blue('Welcome to the program'));
log(chalk.blueBright('Welcome to the program'));
